spring.application.name=inventario

# Puerto de la aplicación
# server.port=8080

# Configuración H2 (base de datos en memoria)
# spring.datasource.url=jdbc:h2:mem:inventariodb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver

# Base de datos (usará variables de entorno de Docker)
# spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/inventariodb
# spring.datasource.username=${DB_USER:postgres}
# spring.datasource.password=${DB_PASS:postgres}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Railway inyecta automáticamente DATABASE_URL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username= # NO es necesario (Railway lo inyecta)
spring.datasource.password= # NO es necesario (Railway lo inyecta)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false   # ponlo en false en producción
server.port=8080

# JPA
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Consola H2 (para verificar datos)
# spring.h2.console.enabled=true
